# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
from ctypes import *
from ctypes.util import find_library as find_library
from typing import Any, Iterable, List, Optional, Protocol, Tuple

NVML_FEATURE_DISABLED: int
NVML_FEATURE_ENABLED: int
NVML_BRAND_UNKNOWN: int
NVML_BRAND_QUADRO: int
NVML_BRAND_TESLA: int
NVML_BRAND_NVS: int
NVML_BRAND_GRID: int
NVML_BRAND_GEFORCE: int
NVML_BRAND_TITAN: int
NVML_BRAND_NVIDIA_VAPPS: int
NVML_BRAND_NVIDIA_VPC: int
NVML_BRAND_NVIDIA_VCS: int
NVML_BRAND_NVIDIA_VWS: int
NVML_BRAND_NVIDIA_VGAMING: int
NVML_BRAND_QUADRO_RTX: int
NVML_BRAND_NVIDIA_RTX: int
NVML_BRAND_NVIDIA: int
NVML_BRAND_GEFORCE_RTX: int
NVML_BRAND_TITAN_RTX: int
NVML_BRAND_COUNT: int
NVML_TEMPERATURE_THRESHOLD_SHUTDOWN: int
NVML_TEMPERATURE_THRESHOLD_SLOWDOWN: int
NVML_TEMPERATURE_THRESHOLD_MEM_MAX: int
NVML_TEMPERATURE_THRESHOLD_GPU_MAX: int
NVML_TEMPERATURE_THRESHOLD_ACOUSTIC_MIN: int
NVML_TEMPERATURE_THRESHOLD_ACOUSTIC_CURR: int
NVML_TEMPERATURE_THRESHOLD_ACOUSTIC_MAX: int
NVML_TEMPERATURE_THRESHOLD_COUNT: int
NVML_TEMPERATURE_GPU: int
NVML_TEMPERATURE_COUNT: int
NVML_COMPUTEMODE_DEFAULT: int
NVML_COMPUTEMODE_EXCLUSIVE_THREAD: int
NVML_COMPUTEMODE_PROHIBITED: int
NVML_COMPUTEMODE_EXCLUSIVE_PROCESS: int
NVML_COMPUTEMODE_COUNT: int
NVML_MEMORY_LOCATION_L1_CACHE: int
NVML_MEMORY_LOCATION_L2_CACHE: int
NVML_MEMORY_LOCATION_DEVICE_MEMORY: int
NVML_MEMORY_LOCATION_DRAM: int
NVML_MEMORY_LOCATION_REGISTER_FILE: int
NVML_MEMORY_LOCATION_TEXTURE_MEMORY: int
NVML_MEMORY_LOCATION_TEXTURE_SHM: int
NVML_MEMORY_LOCATION_CBU: int
NVML_MEMORY_LOCATION_SRAM: int
NVML_MEMORY_LOCATION_COUNT: int
NVML_NVLINK_MAX_LINKS: int
NVML_NVLINK_MAX_LANES = NVML_NVLINK_MAX_LINKS
NVML_NVLINK_ERROR_DL_REPLAY: int
NVML_NVLINK_ERROR_DL_RECOVERY: int
NVML_NVLINK_ERROR_DL_CRC_FLIT: int
NVML_NVLINK_ERROR_DL_CRC_DATA: int
NVML_NVLINK_ERROR_DL_ECC_DATA: int
NVML_NVLINK_ERROR_COUNT: int
NVML_NVLINK_ERROR_DL_ECC_LANE0: int
NVML_NVLINK_ERROR_DL_ECC_LANE1: int
NVML_NVLINK_ERROR_DL_ECC_LANE2: int
NVML_NVLINK_ERROR_DL_ECC_LANE3: int
NVML_NVLINK_ERROR_DL_ECC_COUNT: int
NVML_NVLINK_CAP_P2P_SUPPORTED: int
NVML_NVLINK_CAP_SYSMEM_ACCESS: int
NVML_NVLINK_CAP_P2P_ATOMICS: int
NVML_NVLINK_CAP_SYSMEM_ATOMICS: int
NVML_NVLINK_CAP_SLI_BRIDGE: int
NVML_NVLINK_CAP_VALID: int
NVML_NVLINK_CAP_COUNT: int
NVML_NVLINK_COUNTER_PKTFILTER_NOP: int
NVML_NVLINK_COUNTER_PKTFILTER_READ: int
NVML_NVLINK_COUNTER_PKTFILTER_WRITE: int
NVML_NVLINK_COUNTER_PKTFILTER_RATOM: int
NVML_NVLINK_COUNTER_PKTFILTER_NRATOM: int
NVML_NVLINK_COUNTER_PKTFILTER_FLUSH: int
NVML_NVLINK_COUNTER_PKTFILTER_RESPDATA: int
NVML_NVLINK_COUNTER_PKTFILTER_RESPNODATA: int
NVML_NVLINK_COUNTER_PKTFILTER_ALL: int
NVML_NVLINK_COUNTER_UNIT_CYCLES: int
NVML_NVLINK_COUNTER_UNIT_PACKETS: int
NVML_NVLINK_COUNTER_UNIT_BYTES: int
NVML_NVLINK_COUNTER_UNIT_RESERVED: int
NVML_NVLINK_COUNTER_UNIT_COUNT: int
NVML_NVLINK_DEVICE_TYPE_GPU: int
NVML_NVLINK_DEVICE_TYPE_IBMNPU: int
NVML_NVLINK_DEVICE_TYPE_SWITCH: int
NVML_NVLINK_DEVICE_TYPE_UNKNOWN: int
NVML_SINGLE_BIT_ECC: int
NVML_DOUBLE_BIT_ECC: int
NVML_ECC_ERROR_TYPE_COUNT: int
NVML_VOLATILE_ECC: int
NVML_AGGREGATE_ECC: int
NVML_ECC_COUNTER_TYPE_COUNT: int
NVML_MEMORY_ERROR_TYPE_CORRECTED: int
NVML_MEMORY_ERROR_TYPE_UNCORRECTED: int
NVML_MEMORY_ERROR_TYPE_COUNT: int
NVML_CLOCK_GRAPHICS: int
NVML_CLOCK_SM: int
NVML_CLOCK_MEM: int
NVML_CLOCK_VIDEO: int
NVML_CLOCK_COUNT: int
NVML_CLOCK_ID_CURRENT: int
NVML_CLOCK_ID_APP_CLOCK_TARGET: int
NVML_CLOCK_ID_APP_CLOCK_DEFAULT: int
NVML_CLOCK_ID_CUSTOMER_BOOST_MAX: int
NVML_CLOCK_ID_COUNT: int
NVML_DRIVER_WDDM: int
NVML_DRIVER_WDM: int
NVML_PSTATE_0: int
NVML_PSTATE_1: int
NVML_PSTATE_2: int
NVML_PSTATE_3: int
NVML_PSTATE_4: int
NVML_PSTATE_5: int
NVML_PSTATE_6: int
NVML_PSTATE_7: int
NVML_PSTATE_8: int
NVML_PSTATE_9: int
NVML_PSTATE_10: int
NVML_PSTATE_11: int
NVML_PSTATE_12: int
NVML_PSTATE_13: int
NVML_PSTATE_14: int
NVML_PSTATE_15: int
NVML_PSTATE_UNKNOWN: int
NVML_INFOROM_OEM: int
NVML_INFOROM_ECC: int
NVML_INFOROM_POWER: int
NVML_INFOROM_COUNT: int
NVML_SUCCESS: int
NVML_ERROR_UNINITIALIZED: int
NVML_ERROR_INVALID_ARGUMENT: int
NVML_ERROR_NOT_SUPPORTED: int
NVML_ERROR_NO_PERMISSION: int
NVML_ERROR_ALREADY_INITIALIZED: int
NVML_ERROR_NOT_FOUND: int
NVML_ERROR_INSUFFICIENT_SIZE: int
NVML_ERROR_INSUFFICIENT_POWER: int
NVML_ERROR_DRIVER_NOT_LOADED: int
NVML_ERROR_TIMEOUT: int
NVML_ERROR_IRQ_ISSUE: int
NVML_ERROR_LIBRARY_NOT_FOUND: int
NVML_ERROR_FUNCTION_NOT_FOUND: int
NVML_ERROR_CORRUPTED_INFOROM: int
NVML_ERROR_GPU_IS_LOST: int
NVML_ERROR_RESET_REQUIRED: int
NVML_ERROR_OPERATING_SYSTEM: int
NVML_ERROR_LIB_RM_VERSION_MISMATCH: int
NVML_ERROR_IN_USE: int
NVML_ERROR_MEMORY: int
NVML_ERROR_NO_DATA: int
NVML_ERROR_VGPU_ECC_NOT_SUPPORTED: int
NVML_ERROR_INSUFFICIENT_RESOURCES: int
NVML_ERROR_FREQ_NOT_SUPPORTED: int
NVML_ERROR_UNKNOWN: int
NVML_FAN_NORMAL: int
NVML_FAN_FAILED: int
NVML_LED_COLOR_GREEN: int
NVML_LED_COLOR_AMBER: int
NVML_GOM_ALL_ON: int
NVML_GOM_COMPUTE: int
NVML_GOM_LOW_DP: int
NVML_PAGE_RETIREMENT_CAUSE_MULTIPLE_SINGLE_BIT_ECC_ERRORS: int
NVML_PAGE_RETIREMENT_CAUSE_DOUBLE_BIT_ECC_ERROR: int
NVML_PAGE_RETIREMENT_CAUSE_COUNT: int
NVML_RESTRICTED_API_SET_APPLICATION_CLOCKS: int
NVML_RESTRICTED_API_SET_AUTO_BOOSTED_CLOCKS: int
NVML_RESTRICTED_API_COUNT: int
NVML_BRIDGE_CHIP_PLX: int
NVML_BRIDGE_CHIP_BRO4: int
NVML_MAX_PHYSICAL_BRIDGE: int
NVML_VALUE_TYPE_DOUBLE: int
NVML_VALUE_TYPE_UNSIGNED_INT: int
NVML_VALUE_TYPE_UNSIGNED_LONG: int
NVML_VALUE_TYPE_UNSIGNED_LONG_LONG: int
NVML_VALUE_TYPE_SIGNED_LONG_LONG: int
NVML_VALUE_TYPE_COUNT: int
NVML_PERF_POLICY_POWER: int
NVML_PERF_POLICY_THERMAL: int
NVML_PERF_POLICY_SYNC_BOOST: int
NVML_PERF_POLICY_BOARD_LIMIT: int
NVML_PERF_POLICY_LOW_UTILIZATION: int
NVML_PERF_POLICY_RELIABILITY: int
NVML_PERF_POLICY_TOTAL_APP_CLOCKS: int
NVML_PERF_POLICY_TOTAL_BASE_CLOCKS: int
NVML_PERF_POLICY_COUNT: int
NVML_ENCODER_QUERY_H264: int
NVML_ENCODER_QUERY_HEVC: int
NVML_FBC_SESSION_TYPE_UNKNOWN: int
NVML_FBC_SESSION_TYPE_TOSYS: int
NVML_FBC_SESSION_TYPE_CUDA: int
NVML_FBC_SESSION_TYPE_VID: int
NVML_FBC_SESSION_TYPE_HWENC: int
NVML_DETACH_GPU_KEEP: int
NVML_DETACH_GPU_REMOVE: int
NVML_PCIE_LINK_KEEP: int
NVML_PCIE_LINK_SHUT_DOWN: int
NVML_TOTAL_POWER_SAMPLES: int
NVML_GPU_UTILIZATION_SAMPLES: int
NVML_MEMORY_UTILIZATION_SAMPLES: int
NVML_ENC_UTILIZATION_SAMPLES: int
NVML_DEC_UTILIZATION_SAMPLES: int
NVML_PROCESSOR_CLK_SAMPLES: int
NVML_MEMORY_CLK_SAMPLES: int
NVML_SAMPLINGTYPE_COUNT: int
NVML_PCIE_UTIL_TX_BYTES: int
NVML_PCIE_UTIL_RX_BYTES: int
NVML_PCIE_UTIL_COUNT: int
NVML_TOPOLOGY_INTERNAL: int
NVML_TOPOLOGY_SINGLE: int
NVML_TOPOLOGY_MULTIPLE: int
NVML_TOPOLOGY_HOSTBRIDGE: int
NVML_TOPOLOGY_NODE: int
NVML_TOPOLOGY_CPU = NVML_TOPOLOGY_NODE
NVML_TOPOLOGY_SYSTEM: int
NVML_P2P_CAPS_INDEX_READ: int
NVML_P2P_CAPS_INDEX_WRITE: int
NVML_P2P_CAPS_INDEX_NVLINK: int
NVML_P2P_CAPS_INDEX_ATOMICS: int
NVML_P2P_CAPS_INDEX_PROP: int
NVML_P2P_CAPS_INDEX_LOOPBACK: int
NVML_P2P_CAPS_INDEX_UNKNOWN: int
NVML_P2P_STATUS_OK: int
NVML_P2P_STATUS_CHIPSET_NOT_SUPPORED: int
NVML_P2P_STATUS_GPU_NOT_SUPPORTED: int
NVML_P2P_STATUS_IOH_TOPOLOGY_NOT_SUPPORTED: int
NVML_P2P_STATUS_DISABLED_BY_REGKEY: int
NVML_P2P_STATUS_NOT_SUPPORTED: int
NVML_P2P_STATUS_UNKNOWN: int
NVML_DEVICE_ARCH_KEPLER: int
NVML_DEVICE_ARCH_MAXWELL: int
NVML_DEVICE_ARCH_PASCAL: int
NVML_DEVICE_ARCH_VOLTA: int
NVML_DEVICE_ARCH_TURING: int
NVML_DEVICE_ARCH_AMPERE: int
NVML_DEVICE_ARCH_UNKNOWN: int
NVML_BUS_TYPE_UNKNOWN: int
NVML_BUS_TYPE_PCI: int
NVML_BUS_TYPE_PCIE: int
NVML_BUS_TYPE_FPCI: int
NVML_BUS_TYPE_AGP: int
NVML_CLOCK_LIMIT_ID_RANGE_START: int
NVML_CLOCK_LIMIT_ID_TDP: int
NVML_CLOCK_LIMIT_ID_UNLIMITED: int
NVML_AFFINITY_SCOPE_NODE: int
NVML_AFFINITY_SCOPE_SOCKET: int
nvmlFlagDefault: int
nvmlFlagForce: int
NVML_INIT_FLAG_NO_GPUS: int
NVML_INIT_FLAG_NO_ATTACH: int
NVML_MAX_GPC_COUNT: int
NVML_DEVICE_INFOROM_VERSION_BUFFER_SIZE: int
NVML_DEVICE_UUID_BUFFER_SIZE: int
NVML_DEVICE_UUID_V2_BUFFER_SIZE: int
NVML_SYSTEM_DRIVER_VERSION_BUFFER_SIZE: int
NVML_SYSTEM_NVML_VERSION_BUFFER_SIZE: int
NVML_DEVICE_NAME_BUFFER_SIZE: int
NVML_DEVICE_SERIAL_BUFFER_SIZE: int
NVML_DEVICE_PART_NUMBER_BUFFER_SIZE: int
NVML_DEVICE_VBIOS_VERSION_BUFFER_SIZE: int
NVML_DEVICE_PCI_BUS_ID_BUFFER_SIZE: int
NVML_DEVICE_PCI_BUS_ID_BUFFER_V2_SIZE: int
NVML_GRID_LICENSE_BUFFER_SIZE: int
NVML_VGPU_NAME_BUFFER_SIZE: int
NVML_GRID_LICENSE_FEATURE_MAX_COUNT: int
NVML_VGPU_METADATA_OPAQUE_DATA_SIZE: Any
NVML_VGPU_PGPU_METADATA_OPAQUE_DATA_SIZE: int
NVML_DEVICE_PCI_BUS_ID_LEGACY_FMT: str
NVML_DEVICE_PCI_BUS_ID_FMT: str
NVML_VALUE_NOT_AVAILABLE_ulonglong: Any
NVML_VALUE_NOT_AVAILABLE_uint: Any
NVML_FI_DEV_ECC_CURRENT: int
NVML_FI_DEV_ECC_PENDING: int
NVML_FI_DEV_ECC_SBE_VOL_TOTAL: int
NVML_FI_DEV_ECC_DBE_VOL_TOTAL: int
NVML_FI_DEV_ECC_SBE_AGG_TOTAL: int
NVML_FI_DEV_ECC_DBE_AGG_TOTAL: int
NVML_FI_DEV_ECC_SBE_VOL_L1: int
NVML_FI_DEV_ECC_DBE_VOL_L1: int
NVML_FI_DEV_ECC_SBE_VOL_L2: int
NVML_FI_DEV_ECC_DBE_VOL_L2: int
NVML_FI_DEV_ECC_SBE_VOL_DEV: int
NVML_FI_DEV_ECC_DBE_VOL_DEV: int
NVML_FI_DEV_ECC_SBE_VOL_REG: int
NVML_FI_DEV_ECC_DBE_VOL_REG: int
NVML_FI_DEV_ECC_SBE_VOL_TEX: int
NVML_FI_DEV_ECC_DBE_VOL_TEX: int
NVML_FI_DEV_ECC_DBE_VOL_CBU: int
NVML_FI_DEV_ECC_SBE_AGG_L1: int
NVML_FI_DEV_ECC_DBE_AGG_L1: int
NVML_FI_DEV_ECC_SBE_AGG_L2: int
NVML_FI_DEV_ECC_DBE_AGG_L2: int
NVML_FI_DEV_ECC_SBE_AGG_DEV: int
NVML_FI_DEV_ECC_DBE_AGG_DEV: int
NVML_FI_DEV_ECC_SBE_AGG_REG: int
NVML_FI_DEV_ECC_DBE_AGG_REG: int
NVML_FI_DEV_ECC_SBE_AGG_TEX: int
NVML_FI_DEV_ECC_DBE_AGG_TEX: int
NVML_FI_DEV_ECC_DBE_AGG_CBU: int
NVML_FI_DEV_RETIRED_SBE: int
NVML_FI_DEV_RETIRED_DBE: int
NVML_FI_DEV_RETIRED_PENDING: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L0: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L1: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L2: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L3: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L4: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L5: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L0: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L1: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L2: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L3: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L4: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L5: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L0: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L1: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L2: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L3: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L4: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L5: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L0: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L1: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L2: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L3: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L4: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L5: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L0: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L1: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L2: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L3: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L4: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L5: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_TOTAL: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L0: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L1: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L2: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L3: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L4: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L5: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_TOTAL: int
NVML_FI_DEV_PERF_POLICY_POWER: int
NVML_FI_DEV_PERF_POLICY_THERMAL: int
NVML_FI_DEV_PERF_POLICY_SYNC_BOOST: int
NVML_FI_DEV_PERF_POLICY_BOARD_LIMIT: int
NVML_FI_DEV_PERF_POLICY_LOW_UTILIZATION: int
NVML_FI_DEV_PERF_POLICY_RELIABILITY: int
NVML_FI_DEV_PERF_POLICY_TOTAL_APP_CLOCKS: int
NVML_FI_DEV_PERF_POLICY_TOTAL_BASE_CLOCKS: int
NVML_FI_DEV_MEMORY_TEMP: int
NVML_FI_DEV_TOTAL_ENERGY_CONSUMPTION: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L0: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L1: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L2: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L3: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L4: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L5: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_COMMON: int
NVML_FI_DEV_NVLINK_LINK_COUNT: int
NVML_FI_DEV_RETIRED_PENDING_SBE: int
NVML_FI_DEV_RETIRED_PENDING_DBE: int
NVML_FI_DEV_PCIE_REPLAY_COUNTER: int
NVML_FI_DEV_PCIE_REPLAY_ROLLOVER_COUNTER: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L6: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L7: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L8: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L9: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L10: int
NVML_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L11: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L6: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L7: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L8: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L9: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L10: int
NVML_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L11: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L6: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L7: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L8: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L9: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L10: int
NVML_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L11: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L6: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L7: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L8: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L9: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L10: int
NVML_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L11: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L6: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L7: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L8: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L9: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L10: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C0_L11: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L6: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L7: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L8: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L9: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L10: int
NVML_FI_DEV_NVLINK_BANDWIDTH_C1_L11: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L6: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L7: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L8: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L9: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L10: int
NVML_FI_DEV_NVLINK_SPEED_MBPS_L11: int
NVML_FI_DEV_NVLINK_THROUGHPUT_DATA_TX: int
NVML_FI_DEV_NVLINK_THROUGHPUT_DATA_RX: int
NVML_FI_DEV_NVLINK_THROUGHPUT_RAW_TX: int
NVML_FI_DEV_NVLINK_THROUGHPUT_RAW_RX: int
NVML_FI_DEV_REMAPPED_COR: int
NVML_FI_DEV_REMAPPED_UNC: int
NVML_FI_DEV_REMAPPED_PENDING: int
NVML_FI_DEV_REMAPPED_FAILURE: int
NVML_FI_DEV_NVLINK_REMOTE_NVLINK_ID: int
NVML_FI_DEV_NVSWITCH_CONNECTED_LINK_COUNT: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L0: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L1: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L2: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L3: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L4: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L5: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L6: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L7: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L8: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L9: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L10: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_L11: int
NVML_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_TOTAL: int
NVML_FI_MAX: int
NVML_GPU_VIRTUALIZATION_MODE_NONE: int
NVML_GPU_VIRTUALIZATION_MODE_PASSTHROUGH: int
NVML_GPU_VIRTUALIZATION_MODE_VGPU: int
NVML_GPU_VIRTUALIZATION_MODE_HOST_VGPU: int
NVML_GPU_VIRTUALIZATION_MODE_HOST_VSGA: int
nvmlLib: Any
libLoadLock: Any
NVML_VGPU_VM_ID_DOMAIN_ID: int
NVML_VGPU_VM_ID_UUID: int
NVML_GRID_LICENSE_FEATURE_CODE_UNKNOWN: int
NVML_GRID_LICENSE_FEATURE_CODE_VGPU: int
NVML_GRID_LICENSE_FEATURE_CODE_NVIDIA_RTX: int
NVML_GRID_LICENSE_FEATURE_CODE_VWORKSTATION: int
NVML_GRID_LICENSE_FEATURE_CODE_GAMING: int
NVML_GRID_LICENSE_FEATURE_CODE_COMPUTE: int
NVML_GRID_LICENSE_EXPIRY_NOT_AVAILABLE: int
NVML_GRID_LICENSE_EXPIRY_INVALID: int
NVML_GRID_LICENSE_EXPIRY_VALID: int
NVML_GRID_LICENSE_EXPIRY_NOT_APPLICABLE: int
NVML_GRID_LICENSE_EXPIRY_PERMANENT: int
NVML_VGPU_INSTANCE_GUEST_INFO_STATE_UNINITIALIZED: int
NVML_VGPU_INSTANCE_GUEST_INFO_STATE_INITIALIZED: int
NVML_VGPU_VM_COMPATIBILITY_NONE: int
NVML_VGPU_VM_COMPATIBILITY_COLD: int
NVML_VGPU_VM_COMPATIBILITY_HIBERNATE: int
NVML_VGPU_VM_COMPATIBILITY_SLEEP: int
NVML_VGPU_VM_COMPATIBILITY_LIVE: int
NVML_VGPU_COMPATIBILITY_LIMIT_NONE: int
NVML_VGPU_COMPATIBILITY_LIMIT_HOST_DRIVER: int
NVML_VGPU_COMPATIBILITY_LIMIT_GUEST_DRIVER: int
NVML_VGPU_COMPATIBILITY_LIMIT_GPU: int
NVML_VGPU_COMPATIBILITY_LIMIT_OTHER: int
NVML_HOST_VGPU_MODE_NON_SRIOV: int
NVML_HOST_VGPU_MODE_SRIOV: int

class NVMLError(Exception):
    value: int
    def __new__(typ, value): ...
    def __eq__(self, other): ...

def nvmlExceptionClass(nvmlErrorCode): ...

class nvmlFriendlyObject:
    def __init__(self, dictionary: Any) -> None: ...

def nvmlStructToFriendlyObject(struct: Any): ...
def nvmlFriendlyObjectToStruct(obj: Any, model: Any): ...

class struct_c_nvmlUnit_t(Structure): ...

c_nvmlUnit_t: Any

class _PrintableStructure(Structure): ...
class c_nvmlUnitInfo_t(_PrintableStructure): ...
class c_nvmlLedState_t(_PrintableStructure): ...
class c_nvmlPSUInfo_t(_PrintableStructure): ...
class c_nvmlUnitFanInfo_t(_PrintableStructure): ...
class c_nvmlUnitFanSpeeds_t(_PrintableStructure): ...
class struct_c_nvmlDevice_t(Structure): ...

c_nvmlDevice_t: Any

class nvmlPciInfo_v2_t(_PrintableStructure): ...
class nvmlPciInfo_t(_PrintableStructure): ...
class c_nvmlExcludedDeviceInfo_t(_PrintableStructure): ...
class nvmlNvLinkUtilizationControl_t(_PrintableStructure): ...

class c_nvmlMemory_t(_PrintableStructure):
    total: int
    free: int
    used: int

class c_nvmlBAR1Memory_t(_PrintableStructure): ...
class nvmlClkMonFaultInfo_t(Structure): ...
class nvmlClkMonStatus_t(Structure): ...
class c_nvmlProcessInfo_t(_PrintableStructure): ...

class PnvmlProcessInfo(Protocol):
    pid: int
    usedGpuMemory: int

class c_nvmlBridgeChipInfo_t(_PrintableStructure): ...
class c_nvmlBridgeChipHierarchy_t(_PrintableStructure): ...
class c_nvmlEccErrorCounts_t(_PrintableStructure): ...

class c_nvmlUtilization_t(_PrintableStructure):
    gpu: int
    memory: int

class c_nvmlHwbcEntry_t(_PrintableStructure): ...
class c_nvmlValue_t(Union): ...
class c_nvmlSample_t(_PrintableStructure): ...
class c_nvmlViolationTime_t(_PrintableStructure): ...
class c_nvmlFieldValue_t(_PrintableStructure): ...
class c_nvmlVgpuInstanceUtilizationSample_t(_PrintableStructure): ...
class c_nvmlVgpuProcessUtilizationSample_t(_PrintableStructure): ...
class c_nvmlVgpuLicenseExpiry_t(_PrintableStructure): ...
class c_nvmlVgpuLicenseInfo_t(_PrintableStructure): ...
class c_nvmlEncoderSession_t(_PrintableStructure): ...
class c_nvmlProcessUtilizationSample_t(_PrintableStructure): ...
class c_nvmlGridLicenseExpiry_t(_PrintableStructure): ...
class c_nvmlGridLicensableFeature_v4_t(_PrintableStructure): ...
class c_nvmlGridLicensableFeatures_v4_t(_PrintableStructure): ...
class c_nvmlGridLicensableFeature_v3_t(_PrintableStructure): ...
class c_nvmlGridLicensableFeatures_v3_t(_PrintableStructure): ...
class c_nvmlGridLicensableFeature_v2_t(_PrintableStructure): ...
class c_nvmlGridLicensableFeatures_v2_t(_PrintableStructure): ...
class c_nvmlGridLicensableFeature_t(_PrintableStructure): ...
class c_nvmlGridLicensableFeatures_t(_PrintableStructure): ...
class struct_c_nvmlEventSet_t(Structure): ...

c_nvmlEventSet_t: Any
nvmlEventTypeSingleBitEccError: int
nvmlEventTypeDoubleBitEccError: int
nvmlEventTypePState: int
nvmlEventTypeXidCriticalError: int
nvmlEventTypeClock: int
nvmlEventTypePowerSourceChange: int
nvmlEventMigConfigChange: int
nvmlEventTypeNone: int
nvmlEventTypeAll: Any
nvmlClocksThrottleReasonGpuIdle: int
nvmlClocksThrottleReasonApplicationsClocksSetting: int
nvmlClocksThrottleReasonUserDefinedClocks = (
    nvmlClocksThrottleReasonApplicationsClocksSetting
)
nvmlClocksThrottleReasonSwPowerCap: int
nvmlClocksThrottleReasonHwSlowdown: int
nvmlClocksThrottleReasonSyncBoost: int
nvmlClocksThrottleReasonSwThermalSlowdown: int
nvmlClocksThrottleReasonHwThermalSlowdown: int
nvmlClocksThrottleReasonHwPowerBrakeSlowdown: int
nvmlClocksThrottleReasonDisplayClockSetting: int
nvmlClocksThrottleReasonNone: int
nvmlClocksThrottleReasonAll: Any

class c_nvmlEventData_t(_PrintableStructure): ...
class c_nvmlAccountingStats_t(_PrintableStructure): ...
class c_nvmlVgpuVersion_t(Structure): ...
class c_nvmlVgpuMetadata_t(Structure): ...
class c_nvmlVgpuPgpuMetadata_t(Structure): ...
class c_nvmlVgpuPgpuCompatibility_t(Structure): ...
class c_nvmlFBCStats_t(Structure): ...
class c_nvmlFBCSession_t(_PrintableStructure): ...

NVML_DEVICE_MIG_DISABLE: int
NVML_DEVICE_MIG_ENABLE: int
NVML_GPU_INSTANCE_PROFILE_1_SLICE: int
NVML_GPU_INSTANCE_PROFILE_2_SLICE: int
NVML_GPU_INSTANCE_PROFILE_3_SLICE: int
NVML_GPU_INSTANCE_PROFILE_4_SLICE: int
NVML_GPU_INSTANCE_PROFILE_7_SLICE: int
NVML_GPU_INSTANCE_PROFILE_8_SLICE: int
NVML_GPU_INSTANCE_PROFILE_6_SLICE: int
NVML_GPU_INSTANCE_PROFILE_1_SLICE_REV1: int
NVML_GPU_INSTANCE_PROFILE_COUNT: int

class c_nvmlGpuInstancePlacement_t(Structure): ...
class c_nvmlGpuInstanceProfileInfo_t(Structure): ...
class c_nvmlGpuInstanceInfo_t(Structure): ...
class struct_c_nvmlGpuInstance_t(Structure): ...

c_nvmlGpuInstance_t: Any
NVML_COMPUTE_INSTANCE_PROFILE_1_SLICE: int
NVML_COMPUTE_INSTANCE_PROFILE_2_SLICE: int
NVML_COMPUTE_INSTANCE_PROFILE_3_SLICE: int
NVML_COMPUTE_INSTANCE_PROFILE_4_SLICE: int
NVML_COMPUTE_INSTANCE_PROFILE_7_SLICE: int
NVML_COMPUTE_INSTANCE_PROFILE_8_SLICE: int
NVML_COMPUTE_INSTANCE_PROFILE_6_SLICE: int
NVML_COMPUTE_INSTANCE_PROFILE_COUNT: int
NVML_COMPUTE_INSTANCE_ENGINE_PROFILE_SHARED: int
NVML_COMPUTE_INSTANCE_ENGINE_PROFILE_COUNT: int

class c_nvmlComputeInstancePlacement_t(Structure): ...
class c_nvmlComputeInstanceProfileInfo_t(Structure): ...
class c_nvmlComputeInstanceInfo_t(Structure): ...
class struct_c_nvmlComputeInstance_t(Structure): ...

c_nvmlComputeInstance_t: Any

class c_nvmlDeviceAttributes(Structure): ...
class c_nvmlRowRemapperHistogramValues(Structure): ...

def nvmlInitWithFlags(flags) -> None: ...
def nvmlInit() -> None: ...
def nvmlShutdown() -> None: ...
def nvmlErrorString(result: Any): ...
def nvmlSystemGetNVMLVersion(): ...
def nvmlSystemGetCudaDriverVersion(): ...
def nvmlSystemGetCudaDriverVersion_v2(): ...
def nvmlSystemGetProcessName(pid: Any): ...
def nvmlSystemGetDriverVersion(): ...
def nvmlSystemGetHicVersion(): ...
def nvmlUnitGetCount(): ...
def nvmlUnitGetHandleByIndex(index: Any): ...
def nvmlUnitGetUnitInfo(unit: Any): ...
def nvmlUnitGetLedState(unit: Any): ...
def nvmlUnitGetPsuInfo(unit: Any): ...
def nvmlUnitGetTemperature(unit: Any, type: Any): ...
def nvmlUnitGetFanSpeedInfo(unit: Any): ...
def nvmlUnitGetDeviceCount(unit: Any): ...
def nvmlUnitGetDevices(unit: Any): ...
def nvmlDeviceGetCount(): ...
def nvmlDeviceGetHandleByIndex(index: int) -> c_nvmlDevice_t: ...
def nvmlDeviceGetHandleBySerial(serial: Any): ...
def nvmlDeviceGetHandleByUUID(uuid: Any): ...
def nvmlDeviceGetHandleByPciBusId(pciBusId: Any): ...
def nvmlDeviceGetName(handle: Any): ...
def nvmlDeviceGetBoardId(handle: Any): ...
def nvmlDeviceGetMultiGpuBoard(handle: Any): ...
def nvmlDeviceGetBrand(handle: Any): ...
def nvmlDeviceGetBoardPartNumber(handle: Any): ...
def nvmlDeviceGetSerial(handle: Any): ...
def nvmlDeviceGetMemoryAffinity(handle: Any, nodeSetSize: Any, scope: Any): ...
def nvmlDeviceGetCpuAffinityWithinScope(handle: Any, cpuSetSize: Any, scope: Any): ...
def nvmlDeviceGetCpuAffinity(handle: Any, cpuSetSize: Any): ...
def nvmlDeviceSetCpuAffinity(handle: Any) -> None: ...
def nvmlDeviceClearCpuAffinity(handle: Any) -> None: ...
def nvmlDeviceGetMinorNumber(handle: Any): ...
def nvmlDeviceGetUUID(handle: Any): ...
def nvmlDeviceGetInforomVersion(handle: Any, infoRomObject: Any): ...
def nvmlDeviceGetInforomImageVersion(handle: Any): ...
def nvmlDeviceGetInforomConfigurationChecksum(handle: Any): ...
def nvmlDeviceValidateInforom(handle: Any) -> None: ...
def nvmlDeviceGetDisplayMode(handle: Any): ...
def nvmlDeviceGetDisplayActive(handle: Any): ...
def nvmlDeviceGetPersistenceMode(handle: Any): ...
def nvmlDeviceGetPciInfo_v3(handle: Any): ...
def nvmlDeviceGetPciInfo(handle: Any): ...
def nvmlDeviceGetClockInfo(handle: Any, type: Any): ...
def nvmlDeviceGetMaxClockInfo(handle: Any, type: Any): ...
def nvmlDeviceGetApplicationsClock(handle: c_nvmlDevice_t, type: int) -> int: ...
def nvmlDeviceGetMaxCustomerBoostClock(handle: Any, type: Any): ...
def nvmlDeviceGetClock(handle: Any, type: Any, id): ...
def nvmlDeviceGetDefaultApplicationsClock(handle: Any, type: Any): ...
def nvmlDeviceGetSupportedMemoryClocks(handle: Any): ...
def nvmlDeviceGetSupportedGraphicsClocks(handle: Any, memoryClockMHz: Any): ...
def nvmlDeviceGetFanSpeed(handle: Any): ...
def nvmlDeviceGetFanSpeed_v2(handle: Any, fan): ...
def nvmlDeviceGetTemperature(handle: c_nvmlDevice_t, sensor: int) -> int: ...
def nvmlDeviceGetTemperatureThreshold(handle: Any, threshold: Any): ...
def nvmlDeviceSetTemperatureThreshold(handle: Any, threshold: Any) -> None: ...
def nvmlDeviceGetPowerState(handle: Any): ...
def nvmlDeviceGetPerformanceState(handle: Any): ...
def nvmlDeviceGetPowerManagementMode(handle: Any): ...
def nvmlDeviceGetPowerManagementLimit(handle: Any): ...
def nvmlDeviceGetPowerManagementLimitConstraints(handle: Any): ...
def nvmlDeviceGetPowerManagementDefaultLimit(handle: Any): ...
def nvmlDeviceGetEnforcedPowerLimit(
    handle: c_nvmlDevice_t,
) -> Optional[int]: ...
def nvmlDeviceGetPowerUsage(handle: c_nvmlDevice_t) -> Optional[int]: ...
def nvmlDeviceGetTotalEnergyConsumption(handle: Any): ...
def nvmlDeviceGetGpuOperationMode(handle: Any): ...
def nvmlDeviceGetCurrentGpuOperationMode(handle: Any): ...
def nvmlDeviceGetPendingGpuOperationMode(handle: Any): ...
def nvmlDeviceGetMemoryInfo(handle: c_nvmlDevice_t) -> c_nvmlMemory_t: ...
def nvmlDeviceGetBAR1MemoryInfo(handle: Any): ...
def nvmlDeviceGetComputeMode(handle: Any): ...
def nvmlDeviceGetCudaComputeCapability(handle: Any): ...
def nvmlDeviceGetEccMode(handle: Any): ...
def nvmlDeviceGetCurrentEccMode(handle: Any): ...
def nvmlDeviceGetPendingEccMode(handle: Any): ...
def nvmlDeviceGetTotalEccErrors(
    handle: c_nvmlDevice_t, errorType: int, counterType: int
) -> int: ...
def nvmlDeviceGetDetailedEccErrors(handle: Any, errorType: Any, counterType: Any): ...
def nvmlDeviceGetMemoryErrorCounter(
    handle: Any, errorType: Any, counterType: Any, locationType: Any
): ...
def nvmlDeviceGetUtilizationRates(
    handle: c_nvmlDevice_t,
) -> c_nvmlUtilization_t: ...
def nvmlDeviceGetEncoderUtilization(handle: Any): ...
def nvmlDeviceGetDecoderUtilization(handle: Any): ...
def nvmlDeviceGetPcieReplayCounter(handle: Any): ...
def nvmlDeviceGetDriverModel(handle: Any): ...
def nvmlDeviceGetCurrentDriverModel(handle: Any): ...
def nvmlDeviceGetPendingDriverModel(handle: Any): ...
def nvmlDeviceGetVbiosVersion(handle: Any): ...
def nvmlDeviceGetComputeRunningProcesses_v2(handle: Any): ...
def nvmlDeviceGetComputeRunningProcesses(
    handle: c_nvmlDevice_t,
) -> List[PnvmlProcessInfo]: ...
def nvmlDeviceGetGraphicsRunningProcesses_v2(handle: Any): ...
def nvmlDeviceGetGraphicsRunningProcesses(handle: Any): ...
def nvmlDeviceGetMPSComputeRunningProcesses(handle: Any): ...
def nvmlDeviceGetMPSComputeRunningProcesses_v2(handle: Any): ...
def nvmlDeviceGetAutoBoostedClocksEnabled(handle: Any): ...
def nvmlUnitSetLedState(unit: Any, color: Any) -> None: ...
def nvmlDeviceSetPersistenceMode(handle: Any, mode: Any) -> None: ...
def nvmlDeviceSetComputeMode(handle: Any, mode: Any) -> None: ...
def nvmlDeviceSetEccMode(handle: Any, mode: Any) -> None: ...
def nvmlDeviceClearEccErrorCounts(handle: Any, counterType: Any) -> None: ...
def nvmlDeviceSetDriverModel(handle: Any, model: Any) -> None: ...
def nvmlDeviceSetAutoBoostedClocksEnabled(handle: Any, enabled: Any) -> None: ...
def nvmlDeviceSetDefaultAutoBoostedClocksEnabled(
    handle: Any, enabled: Any, flags: Any
) -> None: ...
def nvmlDeviceSetGpuLockedClocks(
    handle: Any, minGpuClockMHz: Any, maxGpuClockMHz: Any
) -> None: ...
def nvmlDeviceResetGpuLockedClocks(handle: Any) -> None: ...
def nvmlDeviceSetMemoryLockedClocks(
    handle: Any, minMemClockMHz: Any, maxMemClockMHz: Any
) -> None: ...
def nvmlDeviceResetMemoryLockedClocks(handle: Any) -> None: ...
def nvmlDeviceGetClkMonStatus(handle: Any, c_clkMonInfo: Any): ...
def nvmlDeviceSetApplicationsClocks(
    handle: Any, maxMemClockMHz: Any, maxGraphicsClockMHz: Any
) -> None: ...
def nvmlDeviceResetApplicationsClocks(handle: Any) -> None: ...
def nvmlDeviceSetPowerManagementLimit(handle: Any, limit: Any) -> None: ...
def nvmlDeviceSetGpuOperationMode(handle: Any, mode: Any) -> None: ...
def nvmlEventSetCreate(): ...
def nvmlDeviceRegisterEvents(handle: Any, eventTypes: Any, eventSet: Any) -> None: ...
def nvmlDeviceGetSupportedEventTypes(handle: Any): ...
def nvmlEventSetWait_v2(eventSet: Any, timeoutms: Any): ...
def nvmlEventSetWait(eventSet: Any, timeoutms: Any): ...
def nvmlEventSetFree(eventSet: Any) -> None: ...
def nvmlDeviceOnSameBoard(handle1: Any, handle2: Any): ...
def nvmlDeviceGetCurrPcieLinkGeneration(handle: Any): ...
def nvmlDeviceGetMaxPcieLinkGeneration(handle: Any): ...
def nvmlDeviceGetCurrPcieLinkWidth(handle: Any): ...
def nvmlDeviceGetMaxPcieLinkWidth(handle: Any): ...
def nvmlDeviceGetSupportedClocksThrottleReasons(handle: Any): ...
def nvmlDeviceGetCurrentClocksThrottleReasons(handle: Any): ...
def nvmlDeviceGetIndex(handle: Any): ...
def nvmlDeviceGetAccountingMode(handle: Any): ...
def nvmlDeviceSetAccountingMode(handle: Any, mode: Any) -> None: ...
def nvmlDeviceClearAccountingPids(handle: Any) -> None: ...
def nvmlDeviceGetAccountingStats(handle: Any, pid: Any): ...
def nvmlDeviceGetAccountingPids(handle: Any): ...
def nvmlDeviceGetAccountingBufferSize(handle: Any): ...
def nvmlDeviceGetRetiredPages(
    device: c_nvmlDevice_t, sourceFilter: int
) -> Iterable[int]: ...
def nvmlDeviceGetRetiredPages_v2(device: Any, sourceFilter: Any): ...
def nvmlDeviceGetRetiredPagesPendingStatus(device: c_nvmlDevice_t) -> int: ...
def nvmlDeviceGetAPIRestriction(device: Any, apiType: Any): ...
def nvmlDeviceSetAPIRestriction(
    handle: Any, apiType: Any, isRestricted: Any
) -> None: ...
def nvmlDeviceGetBridgeChipInfo(handle: Any): ...
def nvmlDeviceGetSamples(device: Any, sampling_type: Any, timeStamp: Any): ...
def nvmlDeviceGetViolationStatus(device: Any, perfPolicyType: Any): ...
def nvmlDeviceGetPcieThroughput(device: Any, counter: Any): ...
def nvmlSystemGetTopologyGpuSet(cpuNumber: Any): ...
def nvmlDeviceGetTopologyNearestGpus(device: Any, level: Any): ...
def nvmlDeviceGetTopologyCommonAncestor(device1: Any, device2: Any): ...
def nvmlDeviceGetNvLinkUtilizationCounter(device: Any, link: Any, counter: Any): ...
def nvmlDeviceFreezeNvLinkUtilizationCounter(
    device: Any, link: Any, counter: Any, freeze: Any
) -> None: ...
def nvmlDeviceResetNvLinkUtilizationCounter(
    device: Any, link: Any, counter: Any
) -> None: ...
def nvmlDeviceSetNvLinkUtilizationControl(
    device: Any, link: Any, counter: Any, control: Any, reset: Any
) -> None: ...
def nvmlDeviceGetNvLinkUtilizationControl(device: Any, link: Any, counter: Any): ...
def nvmlDeviceGetNvLinkCapability(device: Any, link: Any, capability: Any): ...
def nvmlDeviceGetNvLinkErrorCounter(device: Any, link: Any, counter: Any): ...
def nvmlDeviceResetNvLinkErrorCounters(device: Any, link: Any) -> None: ...
def nvmlDeviceGetNvLinkRemotePciInfo(device: Any, link: Any): ...
def nvmlDeviceGetNvLinkRemoteDeviceType(handle: Any, link: Any): ...
def nvmlDeviceGetNvLinkState(device: Any, link: Any): ...
def nvmlDeviceGetNvLinkVersion(device: Any, link: Any): ...
def nvmlDeviceModifyDrainState(pciInfo: Any, newState: Any) -> None: ...
def nvmlDeviceQueryDrainState(pciInfo: Any): ...
def nvmlDeviceRemoveGpu(pciInfo: Any) -> None: ...
def nvmlDeviceDiscoverGpus(pciInfo: Any) -> None: ...
def nvmlDeviceGetFieldValues(handle: Any, fieldIds: Any): ...
def nvmlDeviceGetVirtualizationMode(handle: Any): ...
def nvmlDeviceSetVirtualizationMode(handle: Any, virtualization_mode: Any): ...
def nvmlDeviceGetSupportedVgpus(handle: Any): ...
def nvmlDeviceGetCreatableVgpus(handle: Any): ...
def nvmlVgpuTypeGetGpuInstanceProfileId(vgpuTypeId: Any): ...
def nvmlVgpuTypeGetClass(vgpuTypeId: Any): ...
def nvmlVgpuTypeGetName(vgpuTypeId: Any): ...
def nvmlVgpuTypeGetDeviceID(vgpuTypeId: Any): ...
def nvmlVgpuTypeGetFramebufferSize(vgpuTypeId: Any): ...
def nvmlVgpuTypeGetNumDisplayHeads(vgpuTypeId: Any): ...
def nvmlVgpuTypeGetResolution(vgpuTypeId: Any): ...
def nvmlVgpuTypeGetLicense(vgpuTypeId: Any): ...
def nvmlVgpuTypeGetFrameRateLimit(vgpuTypeId: Any): ...
def nvmlVgpuTypeGetMaxInstances(handle: Any, vgpuTypeId: Any): ...
def nvmlVgpuTypeGetMaxInstancesPerVm(vgpuTypeId: Any): ...
def nvmlDeviceGetActiveVgpus(handle: Any): ...
def nvmlVgpuInstanceGetVmID(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetUUID(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetMdevUUID(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetVmDriverVersion(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetLicenseStatus(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetLicenseInfo(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetFrameRateLimit(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetEccMode(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetType(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetEncoderCapacity(vgpuInstance: Any): ...
def nvmlVgpuInstanceSetEncoderCapacity(vgpuInstance: Any, encoder_capacity: Any): ...
def nvmlVgpuInstanceGetFbUsage(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetGpuInstanceId(vgpuInstance: Any): ...
def nvmlDeviceGetVgpuUtilization(handle: Any, timeStamp: Any): ...
def nvmlDeviceGetP2PStatus(device1, device2, p2pIndex): ...
def nvmlDeviceGetGridLicensableFeatures_v4(handle: Any): ...
def nvmlDeviceGetGridLicensableFeatures(handle: Any): ...
def nvmlDeviceGetEncoderCapacity(handle: Any, encoderQueryType: Any): ...
def nvmlDeviceGetVgpuProcessUtilization(handle: Any, timeStamp: Any): ...
def nvmlDeviceGetEncoderStats(handle: Any): ...
def nvmlDeviceGetEncoderSessions(handle: Any): ...
def nvmlDeviceGetFBCStats(handle: Any): ...
def nvmlDeviceGetFBCSessions(handle: Any): ...
def nvmlVgpuInstanceGetEncoderStats(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetEncoderSessions(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetFBCStats(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetFBCSessions(vgpuInstance: Any): ...
def nvmlDeviceGetProcessUtilization(handle: Any, timeStamp: Any): ...
def nvmlVgpuInstanceGetMetadata(vgpuInstance: Any): ...
def nvmlDeviceGetVgpuMetadata(handle: Any): ...
def nvmlGetVgpuCompatibility(vgpuMetadata: Any, pgpuMetadata: Any): ...
def nvmlDeviceGetPgpuMetadataString(handle: Any): ...
def nvmlSetVgpuVersion(vgpuVersion: Any): ...
def nvmlGetVgpuVersion(supported: Any, current: Any): ...
def nvmlVgpuInstanceGetAccountingMode(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetAccountingPids(vgpuInstance: Any): ...
def nvmlVgpuInstanceGetAccountingStats(vgpuInstance: Any, pid: Any): ...
def nvmlVgpuInstanceClearAccountingPids(vgpuInstance: Any): ...
def nvmlGetExcludedDeviceCount(): ...
def nvmlGetExcludedDeviceInfoByIndex(index: Any): ...
def nvmlDeviceGetHostVgpuMode(handle: Any): ...
def nvmlDeviceSetMigMode(device: Any, mode: Any): ...
def nvmlDeviceGetMigMode(device: Any): ...
def nvmlDeviceGetGpuInstanceProfileInfo(device: Any, profile: Any): ...
def nvmlDeviceGetGpuInstanceRemainingCapacity(device: Any, profileId: Any): ...
def nvmlDeviceGetGpuInstancePossiblePlacements(
    device: Any, profileId: Any, placementsRef: Any, countRef: Any
): ...
def nvmlDeviceCreateGpuInstance(device: Any, profileId: Any): ...
def nvmlDeviceCreateGpuInstanceWithPlacement(
    device: Any, profileId: Any, placement: Any
): ...
def nvmlGpuInstanceDestroy(gpuInstance: Any): ...
def nvmlDeviceGetGpuInstances(
    device: Any, profileId: Any, gpuInstancesRef: Any, countRef: Any
): ...
def nvmlDeviceGetGpuInstanceById(device: Any, gpuInstanceId: Any): ...
def nvmlGpuInstanceGetInfo(gpuInstance: Any): ...
def nvmlGpuInstanceGetComputeInstanceProfileInfo(
    device: Any, profile: Any, engProfile: Any
): ...
def nvmlGpuInstanceGetComputeInstanceRemainingCapacity(
    gpuInstance: Any, profileId: Any
): ...
def nvmlGpuInstanceCreateComputeInstance(gpuInstance: Any, profileId: Any): ...
def nvmlComputeInstanceDestroy(computeInstance: Any): ...
def nvmlGpuInstanceGetComputeInstances(
    gpuInstance: Any, profileId: Any, computeInstancesRef: Any, countRef: Any
): ...
def nvmlGpuInstanceGetComputeInstanceById(gpuInstance: Any, computeInstanceId: Any): ...
def nvmlComputeInstanceGetInfo_v2(computeInstance: Any): ...
def nvmlComputeInstanceGetInfo(computeInstance: Any): ...
def nvmlDeviceIsMigDeviceHandle(device: Any): ...
def nvmlDeviceGetGpuInstanceId(device: Any): ...
def nvmlDeviceGetComputeInstanceId(device: Any): ...
def nvmlDeviceGetMaxMigDeviceCount(device: Any): ...
def nvmlDeviceGetMigDeviceHandleByIndex(device: Any, index: Any): ...
def nvmlDeviceGetDeviceHandleFromMigDeviceHandle(migDevice: Any): ...
def nvmlDeviceGetAttributes_v2(device: Any): ...
def nvmlDeviceGetAttributes(device: Any): ...
def nvmlDeviceGetRemappedRows(
    device: c_nvmlDevice_t,
) -> Tuple[int, int, int, int]: ...
def nvmlDeviceGetRowRemapperHistogram(device: Any): ...
def nvmlDeviceGetArchitecture(device: Any): ...
def nvmlDeviceGetBusType(device: Any): ...
def nvmlDeviceGetIrqNum(device: Any): ...
