# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
class HealthChecksFeatures:
    disable_check_ssh_certs: bool
    disable_cuda_memtest: bool
    disable_check_zombie: bool
    disable_check_dstate: bool
    disable_link_flap: bool
    disable_xid_errors: bool
    disable_io_errors: bool
    disable_proc_freq: bool
    disable_freq_governor: bool
    disable_check_mem_size: bool
    disable_check_buddyinfo: bool
    disable_ipmi_sel: bool
    disable_hca_count: bool
    disable_disk_usage: bool
    disable_disk_size: bool
    disable_mounted_dir: bool
    disable_file_exists: bool
    disable_dir_exists: bool
    disable_running_process: bool
    disable_check_ssh: bool
    disable_slurm_state: bool
    disable_slrmctld_count: bool
    disable_slurm_cluster_avail: bool
    disable_service_status: bool
    disable_package_version: bool
    disable_nccl_tests: bool
    disable_nvidia_smi: bool
    disable_nvidia_smi_clock_policy: bool
    disable_nvidia_smi_gpu_num: bool
    disable_nvidia_smi_clock_freq: bool
    disable_nvidia_smi_running_procs: bool
    disable_nvidia_smi_running_procs_and_kill: bool
    disable_nvidia_smi_gpu_temp: bool
    disable_nvidia_smi_mem_usage: bool
    disable_nvidia_smi_retired_pages: bool
    disable_nvidia_smi_ecc_uncorrected: bool
    disable_nvidia_smi_ecc_corrected: bool
    disable_nvidia_smi_row_remap: bool
    disable_nvidia_smi_row_remap_pending: bool
    disable_nvidia_smi_row_remap_failed: bool
    disable_nvidia_smi_vbios_mismatch: bool
    disable_dcgmi_diag: bool
    disable_dcgmi_nvlink: bool
    disable_dcgmi_nvlink_error: bool
    disable_dcgmi_nvlink_status: bool
    disable_check_ibstat: bool
    disable_check_ib_interfaces: bool
    disable_check_iblink: bool
    disable_pass_status: bool
    disable_user_access_path_check: bool
    disable_check_uptime: bool
    disable_check_module: bool
    disable_check_dnf_repos: bool
    disable_check_mountpoint: bool
    disable_check_pci: bool
    disable_check_blockdev: bool
    disable_check_ethlink: bool
    disable_check_clocksource: bool
    disable_airstore_credential_count: bool
    disable_check_sensors: bool
